### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by maralzar** [Xzzit/fast-style-transfer#2]
could you please share your final model weight?

**Comment by Xzzit** [comment]
Hi, I have uploaded the pre-trained model in this repo and you can find it on ./pretrained_models/Fauvism_André-Derain_Pier.pth
You can stylize any image by running
```
python stylize_arg.py --content-image ./pretrained_models/bear.jpg --model ./pretrained_models/Fauvism_André-Derain_Pier.pth
```
